language: node_js
node_js:
  - v12
  - v10
cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
